//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MACServices.SecureAd {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiAuthen", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Security")]
    [System.SerializableAttribute()]
    public partial class ApiAuthen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApiKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApiKey {
            get {
                return this.ApiKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ApiKeyField, value) != true)) {
                    this.ApiKeyField = value;
                    this.RaisePropertyChanged("ApiKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAPIRequest", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetAdByPassThroughServiceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetOTPRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.BaseGetAdRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetAdsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetAdsByGroupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetAdRequest))]
    public partial class BaseAPIRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAdByPassThroughServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class GetAdByPassThroughServiceRequest : MACServices.SecureAd.BaseAPIRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HtmlContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HtmlContent {
            get {
                return this.HtmlContentField;
            }
            set {
                if ((object.ReferenceEquals(this.HtmlContentField, value) != true)) {
                    this.HtmlContentField = value;
                    this.RaisePropertyChanged("HtmlContent");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOTPRequest", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.OTP")]
    [System.SerializableAttribute()]
    public partial class GetOTPRequest : MACServices.SecureAd.BaseAPIRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseGetAdRequest", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetAdsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetAdsByGroupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetAdRequest))]
    public partial class BaseGetAdRequest : MACServices.SecureAd.BaseAPIRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MACServices.SecureAd.CampaignProfiling CampaignProfilingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRandomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MACServices.SecureAd.AdType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdReferenceNumber {
            get {
                return this.AdReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AdReferenceNumberField, value) != true)) {
                    this.AdReferenceNumberField = value;
                    this.RaisePropertyChanged("AdReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignId {
            get {
                return this.CampaignIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignIdField, value) != true)) {
                    this.CampaignIdField = value;
                    this.RaisePropertyChanged("CampaignId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignName {
            get {
                return this.CampaignNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignNameField, value) != true)) {
                    this.CampaignNameField = value;
                    this.RaisePropertyChanged("CampaignName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MACServices.SecureAd.CampaignProfiling CampaignProfiling {
            get {
                return this.CampaignProfilingField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignProfilingField, value) != true)) {
                    this.CampaignProfilingField = value;
                    this.RaisePropertyChanged("CampaignProfiling");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignReferenceNumber {
            get {
                return this.CampaignReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignReferenceNumberField, value) != true)) {
                    this.CampaignReferenceNumberField = value;
                    this.RaisePropertyChanged("CampaignReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRandom {
            get {
                return this.IsRandomField;
            }
            set {
                if ((this.IsRandomField.Equals(value) != true)) {
                    this.IsRandomField = value;
                    this.RaisePropertyChanged("IsRandom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MACServices.SecureAd.AdType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAdsRequest", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class GetAdsRequest : MACServices.SecureAd.BaseGetAdRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAdsByGroupRequest", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class GetAdsByGroupRequest : MACServices.SecureAd.BaseGetAdRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupIdField, value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAdRequest", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class GetAdRequest : MACServices.SecureAd.BaseGetAdRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignProfiling", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class CampaignProfiling : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeGroupFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeGroupToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CreditScoreFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CreditScoreToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EthnicityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<MACServices.SecureAd.Gender> GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> HomeOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> HouseholdIncomeFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> HouseholdIncomeToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<MACServices.SecureAd.MaritalStatus> MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AgeGroupFrom {
            get {
                return this.AgeGroupFromField;
            }
            set {
                if ((this.AgeGroupFromField.Equals(value) != true)) {
                    this.AgeGroupFromField = value;
                    this.RaisePropertyChanged("AgeGroupFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AgeGroupTo {
            get {
                return this.AgeGroupToField;
            }
            set {
                if ((this.AgeGroupToField.Equals(value) != true)) {
                    this.AgeGroupToField = value;
                    this.RaisePropertyChanged("AgeGroupTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CreditScoreFrom {
            get {
                return this.CreditScoreFromField;
            }
            set {
                if ((this.CreditScoreFromField.Equals(value) != true)) {
                    this.CreditScoreFromField = value;
                    this.RaisePropertyChanged("CreditScoreFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CreditScoreTo {
            get {
                return this.CreditScoreToField;
            }
            set {
                if ((this.CreditScoreToField.Equals(value) != true)) {
                    this.CreditScoreToField = value;
                    this.RaisePropertyChanged("CreditScoreTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ethnicity {
            get {
                return this.EthnicityField;
            }
            set {
                if ((object.ReferenceEquals(this.EthnicityField, value) != true)) {
                    this.EthnicityField = value;
                    this.RaisePropertyChanged("Ethnicity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<MACServices.SecureAd.Gender> Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> HomeOwner {
            get {
                return this.HomeOwnerField;
            }
            set {
                if ((this.HomeOwnerField.Equals(value) != true)) {
                    this.HomeOwnerField = value;
                    this.RaisePropertyChanged("HomeOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> HouseholdIncomeFrom {
            get {
                return this.HouseholdIncomeFromField;
            }
            set {
                if ((this.HouseholdIncomeFromField.Equals(value) != true)) {
                    this.HouseholdIncomeFromField = value;
                    this.RaisePropertyChanged("HouseholdIncomeFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> HouseholdIncomeTo {
            get {
                return this.HouseholdIncomeToField;
            }
            set {
                if ((this.HouseholdIncomeToField.Equals(value) != true)) {
                    this.HouseholdIncomeToField = value;
                    this.RaisePropertyChanged("HouseholdIncomeTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<MACServices.SecureAd.MaritalStatus> MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((this.MaritalStatusField.Equals(value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdType", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract")]
    public enum AdType : short {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnterOtpScreen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationPage = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MobileMessage = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PassThrough = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Form = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract")]
    public enum Gender : short {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        M = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaritalStatus", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract")]
    public enum MaritalStatus : short {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Married = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAPIResponse", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetAdByPassThroughServiceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetAdFormResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetOTPResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetOTPAdResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetAdResponse))]
    public partial class BaseAPIResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAdByPassThroughServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class GetAdByPassThroughServiceResponse : MACServices.SecureAd.BaseAPIResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MACServices.SecureAd.AdPassThrough PassThroughField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MACServices.SecureAd.AdPassThrough PassThrough {
            get {
                return this.PassThroughField;
            }
            set {
                if ((object.ReferenceEquals(this.PassThroughField, value) != true)) {
                    this.PassThroughField = value;
                    this.RaisePropertyChanged("PassThrough");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAdFormResponse", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class GetAdFormResponse : MACServices.SecureAd.BaseAPIResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MACServices.SecureAd.AdForm AdFormField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MACServices.SecureAd.AdForm AdForm {
            get {
                return this.AdFormField;
            }
            set {
                if ((object.ReferenceEquals(this.AdFormField, value) != true)) {
                    this.AdFormField = value;
                    this.RaisePropertyChanged("AdForm");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOTPResponse", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.OTP")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.GetOTPAdResponse))]
    public partial class GetOTPResponse : MACServices.SecureAd.BaseAPIResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OTPExpireMinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OTPTransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OTPExpireMinutes {
            get {
                return this.OTPExpireMinutesField;
            }
            set {
                if ((this.OTPExpireMinutesField.Equals(value) != true)) {
                    this.OTPExpireMinutesField = value;
                    this.RaisePropertyChanged("OTPExpireMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OTPTransactionId {
            get {
                return this.OTPTransactionIdField;
            }
            set {
                if ((this.OTPTransactionIdField.Equals(value) != true)) {
                    this.OTPTransactionIdField = value;
                    this.RaisePropertyChanged("OTPTransactionId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOTPAdResponse", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class GetOTPAdResponse : MACServices.SecureAd.GetOTPResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MACServices.SecureAd.GetAdResponse AdResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MACServices.SecureAd.GetAdResponse AdResponse {
            get {
                return this.AdResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdResponseField, value) != true)) {
                    this.AdResponseField = value;
                    this.RaisePropertyChanged("AdResponse");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAdResponse", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class GetAdResponse : MACServices.SecureAd.BaseAPIResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MACServices.SecureAd.AdForm AdFormField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MACServices.SecureAd.AdEnterOtpScreen EnterOtpScreenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MACServices.SecureAd.AdMobileMessage MobileMesasgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MACServices.SecureAd.AdType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MACServices.SecureAd.AdVerificationPage VerificationPageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MACServices.SecureAd.AdForm AdForm {
            get {
                return this.AdFormField;
            }
            set {
                if ((object.ReferenceEquals(this.AdFormField, value) != true)) {
                    this.AdFormField = value;
                    this.RaisePropertyChanged("AdForm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MACServices.SecureAd.AdEnterOtpScreen EnterOtpScreen {
            get {
                return this.EnterOtpScreenField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterOtpScreenField, value) != true)) {
                    this.EnterOtpScreenField = value;
                    this.RaisePropertyChanged("EnterOtpScreen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MACServices.SecureAd.AdMobileMessage MobileMesasge {
            get {
                return this.MobileMesasgeField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileMesasgeField, value) != true)) {
                    this.MobileMesasgeField = value;
                    this.RaisePropertyChanged("MobileMesasge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MACServices.SecureAd.AdType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MACServices.SecureAd.AdVerificationPage VerificationPage {
            get {
                return this.VerificationPageField;
            }
            set {
                if ((object.ReferenceEquals(this.VerificationPageField, value) != true)) {
                    this.VerificationPageField = value;
                    this.RaisePropertyChanged("VerificationPage");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdForm", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class AdForm : MACServices.SecureAd.AdBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentHtmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentHtml {
            get {
                return this.ContentHtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentHtmlField, value) != true)) {
                    this.ContentHtmlField = value;
                    this.RaisePropertyChanged("ContentHtml");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdEnterOtpScreen", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class AdEnterOtpScreen : MACServices.SecureAd.AdBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentHtmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentHtml {
            get {
                return this.ContentHtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentHtmlField, value) != true)) {
                    this.ContentHtmlField = value;
                    this.RaisePropertyChanged("ContentHtml");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdMobileMessage", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class AdMobileMessage : MACServices.SecureAd.AdBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashId {
            get {
                return this.HashIdField;
            }
            set {
                if ((object.ReferenceEquals(this.HashIdField, value) != true)) {
                    this.HashIdField = value;
                    this.RaisePropertyChanged("HashId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdVerificationPage", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class AdVerificationPage : MACServices.SecureAd.AdBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentHtmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentHtml {
            get {
                return this.ContentHtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentHtmlField, value) != true)) {
                    this.ContentHtmlField = value;
                    this.RaisePropertyChanged("ContentHtml");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdPassThrough", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    public partial class AdPassThrough : MACServices.SecureAd.AdBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentHtmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentHtml {
            get {
                return this.ContentHtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentHtmlField, value) != true)) {
                    this.ContentHtmlField = value;
                    this.RaisePropertyChanged("ContentHtml");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdBase", Namespace="http://schemas.datacontract.org/2004/07/SAI.Service.API.DataContract.Ad")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.AdForm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.AdEnterOtpScreen))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.AdVerificationPage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.AdMobileMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MACServices.SecureAd.AdPassThrough))]
    public partial class AdBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignId {
            get {
                return this.CampaignIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignIdField, value) != true)) {
                    this.CampaignIdField = value;
                    this.RaisePropertyChanged("CampaignId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecureAd.IAd")]
    public interface IAd {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAd", ReplyAction="http://tempuri.org/IAd/GetAdResponse")]
        MACServices.SecureAd.GetAdResponse GetAd(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAd", ReplyAction="http://tempuri.org/IAd/GetAdResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetAdResponse> GetAdAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetAdWithShortUrlResponse")]
        MACServices.SecureAd.GetAdResponse GetAdWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetAdWithShortUrlResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetAdResponse> GetAdWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetOTPAd", ReplyAction="http://tempuri.org/IAd/GetOTPAdResponse")]
        MACServices.SecureAd.GetOTPAdResponse GetOTPAd(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, MACServices.SecureAd.GetOTPRequest requestOTP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetOTPAd", ReplyAction="http://tempuri.org/IAd/GetOTPAdResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetOTPAdResponse> GetOTPAdAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, MACServices.SecureAd.GetOTPRequest requestOTP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetOTPAdWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetOTPAdWithShortUrlResponse")]
        MACServices.SecureAd.GetOTPAdResponse GetOTPAdWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, MACServices.SecureAd.GetOTPRequest requestOTP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetOTPAdWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetOTPAdWithShortUrlResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetOTPAdResponse> GetOTPAdWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, MACServices.SecureAd.GetOTPRequest requestOTP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetOTPAdByConsumer", ReplyAction="http://tempuri.org/IAd/GetOTPAdByConsumerResponse")]
        MACServices.SecureAd.GetOTPAdResponse GetOTPAdByConsumer(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, string otpConsumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetOTPAdByConsumer", ReplyAction="http://tempuri.org/IAd/GetOTPAdByConsumerResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetOTPAdResponse> GetOTPAdByConsumerAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, string otpConsumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetOTPAdByConsumerWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetOTPAdByConsumerWithShortUrlResponse")]
        MACServices.SecureAd.GetOTPAdResponse GetOTPAdByConsumerWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, string otpConsumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetOTPAdByConsumerWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetOTPAdByConsumerWithShortUrlResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetOTPAdResponse> GetOTPAdByConsumerWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, string otpConsumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdsByGroup", ReplyAction="http://tempuri.org/IAd/GetAdsByGroupResponse")]
        MACServices.SecureAd.GetAdResponse GetAdsByGroup(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdsByGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdsByGroup", ReplyAction="http://tempuri.org/IAd/GetAdsByGroupResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetAdResponse> GetAdsByGroupAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdsByGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdsByGroupWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetAdsByGroupWithShortUrlResponse")]
        MACServices.SecureAd.GetAdResponse GetAdsByGroupWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdsByGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdsByGroupWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetAdsByGroupWithShortUrlResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetAdResponse> GetAdsByGroupWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdsByGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdByPassThroughService", ReplyAction="http://tempuri.org/IAd/GetAdByPassThroughServiceResponse")]
        MACServices.SecureAd.GetAdByPassThroughServiceResponse GetAdByPassThroughService(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdByPassThroughServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdByPassThroughService", ReplyAction="http://tempuri.org/IAd/GetAdByPassThroughServiceResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetAdByPassThroughServiceResponse> GetAdByPassThroughServiceAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdByPassThroughServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdByPassThroughServiceWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetAdByPassThroughServiceWithShortUrlResponse")]
        MACServices.SecureAd.GetAdByPassThroughServiceResponse GetAdByPassThroughServiceWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdByPassThroughServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdByPassThroughServiceWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetAdByPassThroughServiceWithShortUrlResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetAdByPassThroughServiceResponse> GetAdByPassThroughServiceWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdByPassThroughServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdForm", ReplyAction="http://tempuri.org/IAd/GetAdFormResponse")]
        MACServices.SecureAd.GetAdFormResponse GetAdForm(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdForm", ReplyAction="http://tempuri.org/IAd/GetAdFormResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetAdFormResponse> GetAdFormAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdFormWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetAdFormWithShortUrlResponse")]
        MACServices.SecureAd.GetAdFormResponse GetAdFormWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAd/GetAdFormWithShortUrl", ReplyAction="http://tempuri.org/IAd/GetAdFormWithShortUrlResponse")]
        System.Threading.Tasks.Task<MACServices.SecureAd.GetAdFormResponse> GetAdFormWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdChannel : MACServices.SecureAd.IAd, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdClient : System.ServiceModel.ClientBase<MACServices.SecureAd.IAd>, MACServices.SecureAd.IAd {
        
        public AdClient() {
        }
        
        public AdClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MACServices.SecureAd.GetAdResponse GetAd(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request) {
            return base.Channel.GetAd(authen, request);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetAdResponse> GetAdAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request) {
            return base.Channel.GetAdAsync(authen, request);
        }
        
        public MACServices.SecureAd.GetAdResponse GetAdWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request) {
            return base.Channel.GetAdWithShortUrl(authen, request);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetAdResponse> GetAdWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request) {
            return base.Channel.GetAdWithShortUrlAsync(authen, request);
        }
        
        public MACServices.SecureAd.GetOTPAdResponse GetOTPAd(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, MACServices.SecureAd.GetOTPRequest requestOTP) {
            return base.Channel.GetOTPAd(authen, request, requestOTP);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetOTPAdResponse> GetOTPAdAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, MACServices.SecureAd.GetOTPRequest requestOTP) {
            return base.Channel.GetOTPAdAsync(authen, request, requestOTP);
        }
        
        public MACServices.SecureAd.GetOTPAdResponse GetOTPAdWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, MACServices.SecureAd.GetOTPRequest requestOTP) {
            return base.Channel.GetOTPAdWithShortUrl(authen, request, requestOTP);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetOTPAdResponse> GetOTPAdWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, MACServices.SecureAd.GetOTPRequest requestOTP) {
            return base.Channel.GetOTPAdWithShortUrlAsync(authen, request, requestOTP);
        }
        
        public MACServices.SecureAd.GetOTPAdResponse GetOTPAdByConsumer(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, string otpConsumer) {
            return base.Channel.GetOTPAdByConsumer(authen, request, otpConsumer);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetOTPAdResponse> GetOTPAdByConsumerAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, string otpConsumer) {
            return base.Channel.GetOTPAdByConsumerAsync(authen, request, otpConsumer);
        }
        
        public MACServices.SecureAd.GetOTPAdResponse GetOTPAdByConsumerWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, string otpConsumer) {
            return base.Channel.GetOTPAdByConsumerWithShortUrl(authen, request, otpConsumer);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetOTPAdResponse> GetOTPAdByConsumerWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request, string otpConsumer) {
            return base.Channel.GetOTPAdByConsumerWithShortUrlAsync(authen, request, otpConsumer);
        }
        
        public MACServices.SecureAd.GetAdResponse GetAdsByGroup(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdsByGroupRequest request) {
            return base.Channel.GetAdsByGroup(authen, request);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetAdResponse> GetAdsByGroupAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdsByGroupRequest request) {
            return base.Channel.GetAdsByGroupAsync(authen, request);
        }
        
        public MACServices.SecureAd.GetAdResponse GetAdsByGroupWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdsByGroupRequest request) {
            return base.Channel.GetAdsByGroupWithShortUrl(authen, request);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetAdResponse> GetAdsByGroupWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdsByGroupRequest request) {
            return base.Channel.GetAdsByGroupWithShortUrlAsync(authen, request);
        }
        
        public MACServices.SecureAd.GetAdByPassThroughServiceResponse GetAdByPassThroughService(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdByPassThroughServiceRequest request) {
            return base.Channel.GetAdByPassThroughService(authen, request);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetAdByPassThroughServiceResponse> GetAdByPassThroughServiceAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdByPassThroughServiceRequest request) {
            return base.Channel.GetAdByPassThroughServiceAsync(authen, request);
        }
        
        public MACServices.SecureAd.GetAdByPassThroughServiceResponse GetAdByPassThroughServiceWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdByPassThroughServiceRequest request) {
            return base.Channel.GetAdByPassThroughServiceWithShortUrl(authen, request);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetAdByPassThroughServiceResponse> GetAdByPassThroughServiceWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdByPassThroughServiceRequest request) {
            return base.Channel.GetAdByPassThroughServiceWithShortUrlAsync(authen, request);
        }
        
        public MACServices.SecureAd.GetAdFormResponse GetAdForm(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request) {
            return base.Channel.GetAdForm(authen, request);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetAdFormResponse> GetAdFormAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request) {
            return base.Channel.GetAdFormAsync(authen, request);
        }
        
        public MACServices.SecureAd.GetAdFormResponse GetAdFormWithShortUrl(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request) {
            return base.Channel.GetAdFormWithShortUrl(authen, request);
        }
        
        public System.Threading.Tasks.Task<MACServices.SecureAd.GetAdFormResponse> GetAdFormWithShortUrlAsync(MACServices.SecureAd.ApiAuthen authen, MACServices.SecureAd.GetAdRequest request) {
            return base.Channel.GetAdFormWithShortUrlAsync(authen, request);
        }
    }
}
